name: Lint & Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Formatting & Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black ruff

      - name: Syntax and Flake8 Check
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=node_modules,venv,.venv
